services:
  postgres:
    container_name: postgres-sql-wac
    image: postgres:latest
    environment:
      POSTGRES_USER: sayem
      POSTGRES_PASSWORD: sayem123
      POSTGRES_DB: alapon
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - alapon
    restart: unless-stopped

  keycloak:
    container_name: keycloak-wac
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - alapon
    command: ["start-dev"]

networks:
  alapon:
    driver: bridge

volumes:
  postgres:
    driver: local
